name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 24.6.0

      - name: Enable Corepack
        shell: bash
        run: corepack enable

      - name: Install dependencies
        shell: bash
        run: |
          set -ex

          pnpm install --frozen-lockfile --ignore-scripts

      - name: Typecheck
        shell: bash
        run: pnpm run typecheck

      - name: Lint
        shell: bash
        run: pnpm run lint

      - name: Build
        shell: bash
        run: |
          set -ex

          pnpm run build

      - name: Artifact naming
        shell: bash
        run: |
          echo "ARTIFACT_DATESTRING=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "ARTIFACT_OS=$(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: srvb-${{ env.ARTIFACT_OS }}-${{ env.ARTIFACT_DATESTRING }}
          path: |
            native/build/clap/SRVB_artefacts/Release/SRVB.clap
            native/build/clap/SRVB_artefacts/Release/SRVB.vst3
            native/build/clap/SRVB_artefacts/Release/CLAP/
            native/build/clap/SRVB_artefacts/Release/VST3/
            !native/build/clap/SRVB_artefacts/Release/**/*.lib
            !native/build/clap/SRVB_artefacts/Release/**/*.exp
          if-no-files-found: error
